{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "smtp-gateway.fullname" . }}
  labels:
    {{- include "smtp-gateway.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "smtp-gateway.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: http
  endpoints:
  - port: http
    path: /metrics
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
